version: '3.8'

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    container_name: es
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    networks:
      - bible-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    depends_on:
      - es
    networks:
      - bible-net

networks:
  bible-net:
    driver: bridge
